#yml文件不能使用制表符空格tab，只能用普通空格表示缩进
#设置使用  空格（值）
server:
  port: 8080

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1/c83-s2-pfst-damaimarcket?serverTimezone=UTC&CharacterEncoding=UTF-8
     username: root
     password: a
     driver-class-name: com.mysql.jdbc.Driver
#邮件发送  yml配置规则：如果某个阶段有重复配置情况，必要合并
  mail:
      #邮箱服务器地址
      host: smtp.qq.com
      #用户名
      username: 1363121722@qq.com
      #密码
      password: ghqqwswculzsiajh
      default-encoding: utf-8   
 #日志设置
logging:
   level:
      com:
       yc:
        C83pfstSpringBoot:
          dao: debug
          web: warn
             
 #以谁来发送邮件   用户自定义的属性
mail:
     fromMail:
        addr: 1363121722@qq.com